// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission6.Models;

namespace Mission6.Migrations
{
    [DbContext(typeof(TaskContext))]
    partial class TaskContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Mission6.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Home"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "School"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Work"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Church"
                        });
                });

            modelBuilder.Entity("Mission6.Models.TaskForm", b =>
                {
                    b.Property<int>("TaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Important")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaskName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Urgent")
                        .HasColumnType("INTEGER");

                    b.HasKey("TaskID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            TaskID = 1,
                            CategoryID = 4,
                            Completed = false,
                            DueDate = new DateTime(2022, 2, 7, 15, 5, 11, 947, DateTimeKind.Local).AddTicks(7405),
                            Important = false,
                            TaskName = "Read Scriptures",
                            Urgent = true
                        },
                        new
                        {
                            TaskID = 2,
                            CategoryID = 2,
                            Completed = false,
                            DueDate = new DateTime(2022, 2, 7, 15, 5, 11, 952, DateTimeKind.Local).AddTicks(6883),
                            Important = true,
                            TaskName = "404 Homework",
                            Urgent = false
                        },
                        new
                        {
                            TaskID = 3,
                            CategoryID = 1,
                            Completed = false,
                            DueDate = new DateTime(2022, 2, 7, 15, 5, 11, 952, DateTimeKind.Local).AddTicks(7005),
                            Important = false,
                            TaskName = "Clean Dishes",
                            Urgent = false
                        },
                        new
                        {
                            TaskID = 4,
                            CategoryID = 3,
                            Completed = false,
                            DueDate = new DateTime(2022, 2, 7, 15, 5, 11, 952, DateTimeKind.Local).AddTicks(7014),
                            Important = true,
                            TaskName = "Submit Time Correction",
                            Urgent = true
                        });
                });

            modelBuilder.Entity("Mission6.Models.TaskForm", b =>
                {
                    b.HasOne("Mission6.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
